sudo: required
services:
  - docker

before_install:
  - docker build -t sergeyzhylinsky/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run sergeyzhylinsky/react-test npm run test -- --coverage

after_success:
  - docker build -t sergeyzhylinsky/multi-client ./client
  - docker build -t sergeyzhylinsky/multi-nginx ./nginx
  - docker build -t sergeyzhylinsky/multi-server ./server
  - docker build -t sergeyzhylinsky/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push sergeyzhylinsky/multi-client
  - docker push sergeyzhylinsky/multi-nginx
  - docker push sergeyzhylinsky/multi-server
  - docker push sergeyzhylinsky/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MDocker-env
  bucket_name: elasticbeanstalk-us-east-2-962624710381
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY